/**
 * 压缩JS
 */
module.exports = {
	options: {
		banner: '/*! Generated by xApp: <%= abcpkg.name %> */\n',
		beautify: {
			ascii_only: true
		}
	},
	main: {
		files: [
			{
				expand: true,
				cwd: 'build/',
				src: ['**/*_combined.js','config.js'],
				dest: 'build/'
			}
		]
	}
};
