/**
 * 压缩JS
 */
module.exports = function(packageConfig){

	return {
		options: {
			banner: '/*! Generated by xApp: <%= packageConfig.name %> */\n',
			beautify: {
				ascii_only: true
			}
		},
		main: {
			files: [
				{
					expand: true,
					cwd: 'build/',
					src: ['**/*_combined.js','config.js'],
					dest: 'build/'
				}
			]
		}
	};
};



